### ISSUE TITLE
Arelastic::Nodes::Node

### ISSUE THREAD

**Issue by schowdhury** [matthuhiggins/arelastic#22]
Curious to understand reason for naming behind Arelastic::Nodes::Node class.  It seems its methods have nothing to do with an elasticsearch node.  Can you explain that naming choice?

**Comment by malept** [comment]
The naming conventions in this module are intended to be very similar to the [`arel` gem](https://rubygems.org/gems/arel). This makes sense, because this gem is meant to be the Elasticsearch version of `arel`. This should probably be in the README.

With regards to `Arelastic::Nodes::Node`, the analogous class is [`Arel::Nodes::Node`](https://github.com/rails/rails/blob/b23673b4dd399b24bf20edd5d525460fb205459f/activerecord/lib/arel/nodes/node.rb).
